# Mathematical Basis of "Attention is All You Need"

The paper "Attention is All You Need" introduces the Transformer model, which relies entirely on attention mechanisms to handle sequence-to-sequence tasks, such as machine translation, without using recurrent neural networks (RNNs) or convolutional neural networks (CNNs). Here's a detailed explanation of the mathematical basis of the Transformer model:

## 1. Scaled Dot-Product Attention

The scaled dot-product attention mechanism is defined by the formula:

 $\text{Attention}(Q, K, V) = \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right) V $

Here's a breakdown of each component:
- $Q \in \mathbb{R}^{n \times d_k}$: The query matrix, where $n$ is the number of queries and $d_k$ is the dimension of the queries.
- $K \in \mathbb{R}^{m \times d_k}$: The key matrix, where $m$ is the number of keys.
- $V \in \mathbb{R}^{m \times d_v}$: The value matrix, where $d_v$ is the dimension of the values.

The dot product $QK^T$ results in a matrix of size $n \times m$, representing the similarity between each query and each key. Dividing by $\sqrt{d_k}$ helps in stabilizing the gradients during training. The softmax function is applied row-wise to obtain the attention weights, ensuring they sum to one. Finally, these weights are used to compute a weighted sum of the values $V$.

## 2. Multi-Head Attention

Multi-head attention allows the model to attend to different parts of the input simultaneously. It's defined as:

 $\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \ldots, \text{head}_h)W^O $

Each attention head is computed as:

 $\text{head}_i = \text{Attention}(QW_i^Q, KW_i^K, VW_i^V)$

where:
- $W_i^Q \in \mathbb{R}^{d_{model} \times d_k}$: The projection matrix for the queries.
- $W_i^K \in \mathbb{R}^{d_{model} \times d_k}$: The projection matrix for the keys.
- $W_i^V \in \mathbb{R}^{d_{model} \times d_v}$: The projection matrix for the values.
- $W^O \in \mathbb{R}^{hd_v \times d_{model}}$: The projection matrix for the concatenated output of all heads.

The idea is to project the queries, keys, and values into $h$ different learned subspaces and perform scaled dot-product attention in each subspace. The outputs of the $h$ heads are concatenated and linearly transformed to produce the final output.

## 3. Position-wise Feed-Forward Networks

After the attention mechanism, the output goes through a feed-forward neural network, which is applied to each position separately:

 $\text{FFN}(x) = \max(0, xW_1 + b_1)W_2 + b_2$

where:
- $W_1 \in \mathbb{R}^{d_{model} \times d_{ff}}$: The weight matrix for the first linear transformation.
- $b_1 \in \mathbb{R}^{d_{ff}}$: The bias for the first linear transformation.
- $W_2 \in \mathbb{R}^{d_{ff} \times d_{model}}$: The weight matrix for the second linear transformation.
- $b_2 \in \mathbb{R}^{d_{model}}$: The bias for the second linear transformation.

This is essentially a two-layer fully connected network with a ReLU activation in between.

## 4. Positional Encoding

Since the Transformer model does not inherently capture the order of the input sequence, positional encodings are added to the input embeddings to provide information about the position of each token:

$PE_{(pos, 2i)} = \sin\left(\frac{pos}{10000^{2i/d_{model}}}\right)$

$PE_{(pos, 2i+1)} = \cos\left(\frac{pos}{10000^{2i/d_{model}}}\right)$

where $pos$ is the position and $i$ is the dimension. These functions were chosen because they provide unique encodings for each position and can be efficiently computed. They also allow the model to generalize to sequences longer than those seen during training.

## 5. Layer Normalization and Residual Connections

Each sub-layer in the encoder and decoder has a residual connection followed by layer normalization:

$\text{LayerNorm}(x + \text{Sublayer}(x))$

This helps in training deep networks by preventing the vanishing gradient problem and stabilizing the training.

## 6. Encoder and Decoder Structure

### Encoder

Each encoder layer consists of two sub-layers:
1. Multi-head self-attention mechanism.
2. Position-wise feed-forward network.

The encoder processes the input sequence through these layers in a stack.

### Decoder

Each decoder layer consists of three sub-layers:
1. Masked multi-head self-attention mechanism to prevent attending to future positions.
2. Multi-head attention mechanism over the encoder's output.
3. Position-wise feed-forward network.

The decoder generates the output sequence by attending to both the previously generated tokens and the encoder's output.

## 7. Training Objective

The model is trained to minimize the cross-entropy loss between the predicted sequence and the target sequence, using teacher forcing to feed the correct previous token as the next input during training.

By leveraging these components, the Transformer model achieves state-of-the-art performance on various sequence-to-sequence tasks while being highly parallelizable, making it efficient to train on modern hardware.


In [ ]:
!pip install torch==2.0.1 torchtext datasets matplotlib numpy torchviz

  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of torchtext to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 89.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 74.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 39.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━

In [ ]:
import math
import torch
import torch.nn as nn
import torch.optim as optim
from torchtext.data.utils import get_tokenizer
from torchtext.vocab import build_vocab_from_iterator
from datasets import load_dataset
import matplotlib.pyplot as plt
import numpy as np
from torchviz import make_dot

# New variable to control dataset size
dataset_percentage = 0.01  # Use 1% of the dataset. Adjust this value as needed.

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, d_k, d_v, num_heads):
        super().__init__()
        self.num_heads = num_heads
        self.d_model = d_model
        self.d_k = d_k
        self.d_v = d_v

        self.wq = nn.Linear(d_model, d_k * num_heads)
        self.wk = nn.Linear(d_model, d_k * num_heads)
        self.wv = nn.Linear(d_model, d_v * num_heads)
        self.wo = nn.Linear(d_v * num_heads, d_model)

    def forward(self, q, k, v, mask=None):
        batch_size = q.size(0)

        q = self.wq(q).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        k = self.wk(k).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        v = self.wv(v).view(batch_size, -1, self.num_heads, self.d_v).transpose(1, 2)

        attn_scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.d_k)
        if mask is not None:
            attn_scores = attn_scores.masked_fill(mask == 0, float('-inf'))
        self.attn_probs = torch.softmax(attn_scores, dim=-1)

        output = torch.matmul(self.attn_probs, v)
        output = output.transpose(1, 2).contiguous().view(batch_size, -1, self.d_v * self.num_heads)
        return self.wo(output)

class PositionwiseFeedForward(nn.Module):
    def __init__(self, d_model, d_ff):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.ReLU(),
            nn.Linear(d_ff, d_model)
        )

    def forward(self, x):
        return self.fc(x)

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0).transpose(0, 1)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:x.size(0), :]

class EncoderLayer(nn.Module):
    def __init__(self, d_model, d_k, d_v, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, d_k, d_v, num_heads)
        self.feed_forward = PositionwiseFeedForward(d_model, d_ff)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, mask)))
        x = self.norm2(x + self.dropout(self.feed_forward(x)))
        return x

class DecoderLayer(nn.Module):
    def __init__(self, d_model, d_k, d_v, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, d_k, d_v, num_heads)
        self.cross_attn = MultiHeadAttention(d_model, d_k, d_v, num_heads)
        self.feed_forward = PositionwiseFeedForward(d_model, d_ff)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_output, src_mask, tgt_mask):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, tgt_mask)))
        x = self.norm2(x + self.dropout(self.cross_attn(x, enc_output, enc_output, src_mask)))
        x = self.norm3(x + self.dropout(self.feed_forward(x)))
        return x

class Transformer(nn.Module):
    def __init__(self, vocab_size, d_model, d_k, d_v, num_heads, num_layers, d_ff, max_seq_len, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.positional_encoding = PositionalEncoding(d_model, max_seq_len)
        self.encoder_layers = nn.ModuleList([EncoderLayer(d_model, d_k, d_v, num_heads, d_ff, dropout) for _ in range(num_layers)])
        self.decoder_layers = nn.ModuleList([DecoderLayer(d_model, d_k, d_v, num_heads, d_ff, dropout) for _ in range(num_layers)])
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(d_model, vocab_size)

    def forward(self, src, tgt):
        src_mask = (src != 0).unsqueeze(1).unsqueeze(2)
        tgt_mask = (tgt != 0).unsqueeze(1).unsqueeze(2)

        src = self.embedding(src) * math.sqrt(self.embedding.embedding_dim)
        tgt = self.embedding(tgt) * math.sqrt(self.embedding.embedding_dim)

        src = self.positional_encoding(src)
        tgt = self.positional_encoding(tgt)

        src = self.dropout(src)
        tgt = self.dropout(tgt)

        for layer in self.encoder_layers:
            src = layer(src, src_mask)

        for layer in self.decoder_layers:
            tgt = layer(tgt, src, src_mask, tgt_mask)

        return self.fc(tgt)

def yield_tokens(data_iter):
    for text in data_iter:
        yield tokenizer(text['text'])

def data_process(examples):
    return [torch.tensor([vocab[token] for token in tokenizer(example)], dtype=torch.long)
            for example in examples['text']]

def batchify(data, bsz):
    data = torch.cat(data)
    nbatch = data.size(0) // bsz
    data = data.narrow(0, 0, nbatch * bsz)
    data = data.view(bsz, -1).t().contiguous()
    return data

def get_batch(source, i, bptt):
    seq_len = min(bptt, len(source) - 1 - i)
    data = source[i:i+seq_len]
    target = source[i+1:i+1+seq_len].reshape(-1)
    return data, target

print("Loading WikiText-2 dataset...")
dataset = load_dataset("wikitext", "wikitext-2-v1")

# Set up tokenizer
tokenizer = get_tokenizer('basic_english')

# Build vocabulary
print("Building vocabulary...")
vocab = build_vocab_from_iterator(yield_tokens(dataset['train']), specials=['<unk>'])
vocab.set_default_index(vocab['<unk>'])

# Process the data
print("Processing data...")
def process_subset(data, percentage):
    processed = data_process(data)
    subset_size = int(len(processed) * percentage)
    return processed[:subset_size]

train_data = process_subset(dataset['train'], dataset_percentage)
val_data = process_subset(dataset['validation'], dataset_percentage)
test_data = process_subset(dataset['test'], dataset_percentage)

batch_size = 20
eval_batch_size = 10
train_data = batchify(train_data, batch_size)
val_data = batchify(val_data, eval_batch_size)
test_data = batchify(test_data, eval_batch_size)

# Model parameters
vocab_size = len(vocab)
d_model = 512
d_k = 64  # Dimension of key and query vectors
d_v = 64  # Dimension of value vectors
num_heads = 8
num_layers = 6
d_ff = 2048
max_seq_len = 5000
dropout = 0.1

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Transformer(vocab_size, d_model, d_k, d_v, num_heads, num_layers, d_ff, max_seq_len, dropout).to(device)

# Visualize the model architecture
sample_src = torch.randint(0, vocab_size, (10, 32)).to(device)  # (seq_len, batch_size)
sample_tgt = torch.randint(0, vocab_size, (10, 32)).to(device)  # (seq_len, batch_size)

output = model(sample_src, sample_tgt)

dot = make_dot(output, params=dict(model.named_parameters()))
dot.render("transformer_architecture", format="png")

Loading WikiText-2 dataset...
Building vocabulary...
Processing data...


dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.735461 to fit


'transformer_architecture.png'

In [ ]:
# ... (previous code remains unchanged)
import time
# Training function
def train(model, train_data, val_data, epochs, bptt, lr, clip):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.95)

    best_val_loss = float('inf')
    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        total_loss = 0.
        start_time = time.time()

        for batch, i in enumerate(range(0, train_data.size(0) - 1, bptt)):
            data, targets = get_batch(train_data, i, bptt)
            data, targets = data.to(device), targets.to(device)

            optimizer.zero_grad()
            output = model(data, data)  # Using the same data for src and tgt in language modeling
            loss = criterion(output.view(-1, vocab_size), targets)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
            optimizer.step()

            total_loss += loss.item()

            if batch % 200 == 0 and batch > 0:
                cur_loss = total_loss / 200
                elapsed = time.time() - start_time
                print(f'| epoch {epoch:3d} | {batch:5d}/{len(train_data) // bptt:5d} batches | '
                      f'lr {scheduler.get_last_lr()[0]:02.5f} | ms/batch {elapsed * 1000 / 200:5.2f} | '
                      f'loss {cur_loss:5.2f} | ppl {math.exp(cur_loss):8.2f}')
                total_loss = 0
                start_time = time.time()

        val_loss = evaluate(model, val_data, bptt)
        print(f'| End of epoch {epoch:3d} | valid loss {val_loss:5.2f} | '
              f'valid ppl {math.exp(val_loss):8.2f}')

        train_losses.append(total_loss / (len(train_data) // bptt))
        val_losses.append(val_loss)

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best_model.pt')

        scheduler.step()

    return train_losses, val_losses

# Evaluation function
def evaluate(model, data_source, bptt):
    model.eval()
    total_loss = 0.
    criterion = nn.CrossEntropyLoss()

    with torch.no_grad():
        for i in range(0, data_source.size(0) - 1, bptt):
            data, targets = get_batch(data_source, i, bptt)
            data, targets = data.to(device), targets.to(device)
            output = model(data, data)
            total_loss += criterion(output.view(-1, vocab_size), targets).item() * len(data)

    return total_loss / (len(data_source) - 1)

# Prediction function
def predict(model, text, max_len=50):
    model.eval()
    tokens = tokenizer(text)
    input_ids = torch.tensor([vocab[token] for token in tokens]).unsqueeze(0).to(device)

    with torch.no_grad():
        for _ in range(max_len):
            output = model(input_ids, input_ids)
            next_token_id = output[0, -1, :].argmax().item()
            input_ids = torch.cat([input_ids, torch.tensor([[next_token_id]]).to(device)], dim=1)

            if next_token_id == vocab['<eos>']:
                break

    predicted_tokens = [vocab.get_itos()[id] for id in input_ids[0]]
    return ' '.join(predicted_tokens)

# Training parameters
epochs = 10
bptt = 35  # sequence length
lr = 0.0001
clip = 0.25

# Train the model
print("Training the model...")
train_losses, val_losses = train(model, train_data, val_data, epochs, bptt, lr, clip)

# Plot training and validation losses
plt.figure(figsize=(10, 5))
plt.plot(train_losses, label='Training Loss')
plt.plot(val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Losses')
plt.legend()
plt.savefig('loss_plot.png')
plt.close()

# Evaluate on test data
test_loss = evaluate(model, test_data, bptt)
print(f'| Test loss {test_loss:5.2f} | Test ppl {math.exp(test_loss):8.2f}')

# Example prediction
input_text = "The quick brown fox"
predicted_text = predict(model, input_text)
print(f"Input: {input_text}")
print(f"Predicted: {predicted_text}")

Training the model...
| End of epoch   0 | valid loss  8.01 | valid ppl  3024.83
| End of epoch   1 | valid loss  7.26 | valid ppl  1427.78
| End of epoch   2 | valid loss  6.95 | valid ppl  1046.39
| End of epoch   3 | valid loss  6.87 | valid ppl   966.06
| End of epoch   4 | valid loss  6.80 | valid ppl   897.41
| End of epoch   5 | valid loss  6.78 | valid ppl   879.67
| End of epoch   6 | valid loss  6.77 | valid ppl   875.21
| End of epoch   7 | valid loss  6.77 | valid ppl   869.02
| End of epoch   8 | valid loss  6.77 | valid ppl   873.11
| End of epoch   9 | valid loss  6.78 | valid ppl   879.79
| Test loss  6.93 | Test ppl  1020.01
Input: The quick brown fox
Predicted: the quick brown fox , the blue jackets ' s . the blue jackets ' s . the game ' s . the game ' s . the game ' s . the game ' s . the game . the game ' s . the game . the game . the game '


This `MultiHeadAttention` class in PyTorch implements the multi-head attention mechanism, a core component of the Transformer architecture. Below is a line-by-line breakdown of the mathematical basis behind each part of the code:

### Constructor (`__init__` method)
1. **`class MultiHeadAttention(nn.Module):`**
   - This defines a PyTorch neural network module named `MultiHeadAttention`, which represents the multi-head attention mechanism.

2. **`def __init__(self, d_model, d_k, d_v, num_heads):`**
   - The constructor initializes the `MultiHeadAttention` class with four parameters: `d_model`, `d_k`, `d_v`, and `num_heads`.
     - $d_{\text{model}}$: The dimension of the model (input/output dimensionality).
     - $d_k$: The dimensionality of the queries and keys.
     - $d_v$: The dimensionality of the values.
     - `num_heads`: The number of attention heads.

3. **`super().__init__()`**
   - Calls the constructor of the parent class `nn.Module` to initialize the module's internal states.

4. **`self.num_heads = num_heads`**
   - Stores the number of attention heads as an instance variable.

5. **`self.d_model = d_model`, `self.d_k = d_k`, `self.d_v = d_v`**
   - Stores the input model dimension ($d_{\text{model}}$), query/key dimension ($d_k$), and value dimension ($d_v$) as instance variables.

6. **`self.wq = nn.Linear(d_model, d_k * num_heads)`**
   - Defines a linear layer to project the input (`q`) from the model dimension ($d_{\text{model}}$) to the concatenated dimensions of the queries across all attention heads ($d_k \times \text{num\_heads}$).
     - This step corresponds to the creation of the query matrix $QW_i^Q$ in multi-head attention.

7. **`self.wk = nn.Linear(d_model, d_k * num_heads)`**
   - Defines a linear layer to project the input (`k`) from the model dimension ($d_{\text{model}}$) to the concatenated dimensions of the keys across all attention heads ($d_k \times \text{num\_heads}$).
     - This corresponds to the creation of the key matrix $KW_i^K$.

8. **`self.wv = nn.Linear(d_model, d_v * num_heads)`**
   - Defines a linear layer to project the input (`v`) from the model dimension ($d_{\text{model}}$) to the concatenated dimensions of the values across all attention heads ($d_v \times \text{num\_heads}$).
     - This corresponds to the creation of the value matrix $VW_i^V$.

9. **`self.wo = nn.Linear(d_v * num_heads, d_model)`**
   - Defines a linear layer that transforms the concatenated outputs from all attention heads back to the model dimension ($d_{\text{model}}$).
     - This step corresponds to applying the projection matrix $W^O$ in multi-head attention.

### Forward Pass (`forward` method)
1. **`def forward(self, q, k, v, mask=None):`**
   - This defines the forward pass of the multi-head attention module. It takes in queries (`q`), keys (`k`), values (`v`), and an optional attention mask (`mask`).

2. **`batch_size = q.size(0)`**
   - Extracts the batch size from the query tensor `q`, assuming that `q` has the shape $[\text{batch\_size}, \text{sequence\_length}, d_{\text{model}}]$.

3. **`q = self.wq(q).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)`**
   - Projects the input `q` using the `wq` linear layer to transform it from $[\text{batch\_size}, \text{sequence\_length}, d_{\text{model}}]$ to $[\text{batch\_size}, \text{sequence\_length}, \text{num\_heads} \times d_k]$.
   - Then reshapes it to $[\text{batch\_size}, \text{num\_heads}, \text{sequence\_length}, d_k]$ and transposes the dimensions to allow for multi-head parallelism.
     - This corresponds to creating multiple query matrices for different attention heads.

4. **`k = self.wk(k).view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)`**
   - Similar to the above step, projects the input `k` using the `wk` linear layer, reshapes it to $[\text{batch\_size}, \text{num\_heads}, \text{sequence\_length}, d_k]$, and transposes it for multi-head parallelism.
     - This corresponds to creating multiple key matrices for different attention heads.

5. **`v = self.wv(v).view(batch_size, -1, self.num_heads, self.d_v).transpose(1, 2)`**
   - Similarly, projects the input `v` using the `wv` linear layer, reshapes it to $[\text{batch\_size}, \text{num\_heads}, \text{sequence\_length}, d_v]$, and transposes it for multi-head parallelism.
     - This corresponds to creating multiple value matrices for different attention heads.

6. **`attn_scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.d_k)`**
   - Computes the scaled dot-product attention scores by performing a matrix multiplication between `q` and the transposed `k`, resulting in attention scores of shape $[\text{batch\_size}, \text{num\_heads}, \text{sequence\_length}, \text{sequence\_length}]$.
   - Divides by the square root of $d_k$ to scale the scores, stabilizing gradients during training as described in the paper.
     - Mathematically, this corresponds to computing the similarity $ \frac{QK^T}{\sqrt{d_k}} $.

7. **`if mask is not None:`**
   - Checks if a mask is provided. Masks are typically used to prevent attention to certain positions (e.g., padding tokens or future tokens in sequence generation).

8. **`attn_scores = attn_scores.masked_fill(mask == 0, float('-inf'))`**
   - If a mask is provided, sets the attention scores of masked positions to negative infinity, effectively preventing them from contributing to the attention weights.

9. **`self.attn_probs = torch.softmax(attn_scores, dim=-1)`**
   - Applies the softmax function to the attention scores along the last dimension (across sequence length) to convert the scores into normalized attention probabilities.
     - This corresponds to applying the softmax function in the scaled dot-product attention formula.

10. **`output = torch.matmul(self.attn_probs, v)`**
    - Computes the weighted sum of the values `v` based on the attention probabilities, resulting in the attended output of shape $[\text{batch\_size}, \text{num\_heads}, \text{sequence\_length}, d_v]$.
      - This corresponds to the final step in the scaled dot-product attention formula: $ \text{softmax}\left(\frac{QK^T}{\sqrt{d_k}}\right) V $.

11. **`output = output.transpose(1, 2).contiguous().view(batch_size, -1, self.d_v * self.num_heads)`**
    - Transposes the dimensions back to $[\text{batch\_size}, \text{sequence\_length}, \text{num\_heads}, d_v]$, reshapes the output to combine the heads into a single dimension $[\text{batch\_size}, \text{sequence\_length}, \text{num\_heads} \times d_v]$, and ensures that the tensor is contiguous in memory.

12. **`return self.wo(output)`**
    - Finally, applies the `wo` linear layer to project the concatenated output back to the model dimension ($d_{\text{model}}$), producing the final output of the multi-head attention mechanism.
      - This corresponds to the application of the projection matrix $W^O$ in multi-head attention.

This class efficiently implements multi-head attention by splitting the input into multiple heads, performing scaled dot-product attention for each head, and then concatenating and projecting the results back into the model's dimensionality.


In [ ]:
import torch
import torch.nn as nn
import math

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, d_k, d_v, num_heads):
        """
        Initialize the Multi-Head Attention module.

        Args:
        - d_model: Dimensionality of the input and output (model dimension)
        - d_k: Dimensionality of keys
        - d_v: Dimensionality of values
        - num_heads: Number of parallel attention heads
        """
        super().__init__()
        self.num_heads = num_heads
        self.d_model = d_model
        self.d_k = d_k
        self.d_v = d_v

        # Linear projections for Query (Q), Key (K), and Value (V)
        self.wq = nn.Linear(d_model, d_k * num_heads)
        self.wk = nn.Linear(d_model, d_k * num_heads)
        self.wv = nn.Linear(d_model, d_v * num_heads)

        # Final output projection
        self.wo = nn.Linear(d_v * num_heads, d_model)

    def split_heads(self, x, batch_size):
        """
        Split the last dimension into (num_heads, depth).
        Transpose the result such that the shape is (batch_size, num_heads, seq_len, depth)

        Args:
        - x: Input tensor of shape (batch_size, seq_len, d_model)
        - batch_size: Size of the batch

        Returns:
        - Tensor of shape (batch_size, num_heads, seq_len, d_k) or (batch_size, num_heads, seq_len, d_v)
        """
        # Reshape to (batch_size, seq_len, num_heads, depth)
        x = x.view(batch_size, -1, self.num_heads, x.size(-1) // self.num_heads)

        # Transpose to (batch_size, num_heads, seq_len, depth)
        return x.transpose(1, 2)

    def scaled_dot_product_attention(self, q, k, v, mask=None):
        """
        Calculate the attention weights.

        Args:
        - q: query shape == (batch_size, num_heads, seq_len_q, d_k)
        - k: key shape == (batch_size, num_heads, seq_len_k, d_k)
        - v: value shape == (batch_size, num_heads, seq_len_v, d_v)
        - mask: Optional mask shape == (batch_size, 1, 1, seq_len_k)

        Returns:
        - output: shape == (batch_size, num_heads, seq_len_q, d_v)
        - attention_weights: shape == (batch_size, num_heads, seq_len_q, seq_len_k)
        """

        # Calculate attention scores
        # (batch_size, num_heads, seq_len_q, d_k) @ (batch_size, num_heads, d_k, seq_len_k)
        # -> (batch_size, num_heads, seq_len_q, seq_len_k)
        matmul_qk = torch.matmul(q, k.transpose(-2, -1))

        # Scale matmul_qk
        dk = torch.tensor(self.d_k, dtype=torch.float32)
        scaled_attention_logits = matmul_qk / torch.sqrt(dk)

        # Add the mask to the scaled tensor (if provided)
        if mask is not None:
            scaled_attention_logits += (mask * -1e9)

        # Softmax is normalized on the last axis (seq_len_k) so that the scores add up to 1
        # (batch_size, num_heads, seq_len_q, seq_len_k)
        attention_weights = torch.softmax(scaled_attention_logits, dim=-1)

        # Calculate the attention output
        # (batch_size, num_heads, seq_len_q, seq_len_k) @ (batch_size, num_heads, seq_len_v, d_v)
        # -> (batch_size, num_heads, seq_len_q, d_v)
        output = torch.matmul(attention_weights, v)

        return output, attention_weights

    def forward(self, q, k, v, mask=None):
        """
        Forward pass of the multi-head attention layer.

        Args:
        - q: Query tensor of shape (batch_size, seq_len, d_model)
        - k: Key tensor of shape (batch_size, seq_len, d_model)
        - v: Value tensor of shape (batch_size, seq_len, d_model)
        - mask: Optional mask tensor

        Returns:
        - Output tensor of shape (batch_size, seq_len, d_model)
        """
        batch_size = q.size(0)

        # Linear projections and split heads
        # (batch_size, seq_len, d_model) -> (batch_size, seq_len, d_k * num_heads)
        # -> (batch_size, num_heads, seq_len, d_k)
        q = self.split_heads(self.wq(q), batch_size)
        k = self.split_heads(self.wk(k), batch_size)
        v = self.split_heads(self.wv(v), batch_size)

        # Apply scaled dot-product attention
        # scaled_attention shape: (batch_size, num_heads, seq_len, d_v)
        # self.attention_weights shape: (batch_size, num_heads, seq_len, seq_len)
        scaled_attention, self.attention_weights = self.scaled_dot_product_attention(q, k, v, mask)

        # Concatenate heads and prepare for final linear projection
        # Step 1: Transpose the scaled attention output
        # (batch_size, num_heads, seq_len, d_v) -> (batch_size, seq_len, num_heads, d_v)
        transposed_attention = scaled_attention.transpose(1, 2)

        # Step 2: Ensure the tensor is contiguous in memory
        # Shape remains (batch_size, seq_len, num_heads, d_v)
        contiguous_attention = transposed_attention.contiguous()

        # Step 3: Reshape the tensor to concatenate the heads
        # (batch_size, seq_len, num_heads, d_v) -> (batch_size, seq_len, num_heads * d_v)
        concat_attention = contiguous_attention.view(batch_size, -1, self.d_v * self.num_heads)

        # Comments on dimensions:
        # - batch_size: number of sequences in the batch
        # - seq_len: length of each sequence (inferred with -1 in view())
        # - num_heads * d_v: total dimension across all heads
        #   This combines the separate heads into one larger representation

        # Apply final linear projection
        # (batch_size, seq_len, d_v * num_heads) -> (batch_size, seq_len, d_model)
        output = self.wo(concat_attention)

        return output

# Example usage with shape visualization
def example_usage():
    # Set up parameters
    d_model = 512
    d_k = 64
    d_v = 64
    num_heads = 8
    batch_size = 32
    seq_len = 10

    # Instantiate the MultiHeadAttention module
    mha = MultiHeadAttention(d_model, d_k, d_v, num_heads)

    # Create dummy input tensors
    q = torch.randn(batch_size, seq_len, d_model)
    k = torch.randn(batch_size, seq_len, d_model)
    v = torch.randn(batch_size, seq_len, d_model)

    print("Input shapes:")
    print(f"q: {q.shape}")
    print(f"k: {k.shape}")
    print(f"v: {v.shape}")

    # Forward pass
    output = mha(q, k, v)

    print("\nOutput shape:")
    print(f"output: {output.shape}")

    print("\nAttention weights shape:")
    print(f"attention_weights: {mha.attention_weights.shape}")

    # Visualization of internal tensor shapes
    print("\nInternal tensor shapes:")
    print(f"After linear projection (e.g., q): {mha.wq(q).shape}")
    print(f"After splitting heads (e.g., q): {mha.split_heads(mha.wq(q), batch_size).shape}")

    # Scaled dot-product attention
    scaled_attention, _ = mha.scaled_dot_product_attention(
        mha.split_heads(mha.wq(q), batch_size),
        mha.split_heads(mha.wk(k), batch_size),
        mha.split_heads(mha.wv(v), batch_size)
    )
    print(f"Scaled attention output: {scaled_attention.shape}")

    # Concatenation steps
    transposed = scaled_attention.transpose(1, 2)
    print(f"After transpose: {transposed.shape}")

    contiguous = transposed.contiguous()
    print(f"After contiguous: {contiguous.shape}")

    concatenated = contiguous.view(batch_size, -1, d_v * num_heads)
    print(f"After concatenation: {concatenated.shape}")

if __name__ == "__main__":
    example_usage()

Input shapes:
q: torch.Size([32, 10, 512])
k: torch.Size([32, 10, 512])
v: torch.Size([32, 10, 512])

Output shape:
output: torch.Size([32, 10, 512])

Attention weights shape:
attention_weights: torch.Size([32, 8, 10, 10])

Internal tensor shapes:
After linear projection (e.g., q): torch.Size([32, 10, 512])
After splitting heads (e.g., q): torch.Size([32, 8, 10, 64])
Scaled attention output: torch.Size([32, 8, 10, 64])
After transpose: torch.Size([32, 10, 8, 64])
After contiguous: torch.Size([32, 10, 8, 64])
After concatenation: torch.Size([32, 10, 512])


### Attention Mechanism Explanation with Multi-Dimensional Example

The attention mechanism is a core component in models like the Transformer, where it allows the model to focus on different parts of the input sequence based on the relevance to a given task. The mechanism operates on three key components: **Query (Q)**, **Key (K)**, and **Value (V)**, which have specific roles and dimensions that facilitate the computation of attention scores and the final output.

#### Roles of Query, Key, and Value

1. **Query (Q):** Represents what the model is trying to find or match. It acts as a "search pattern" that helps the attention mechanism determine which parts of the input are most relevant.
2. **Key (K):** Serves as an identifier or feature to determine how relevant each value is to the query. The key is compared to the query to compute attention scores, which assign weights to the values.
3. **Value (V):** Represents the actual input data (or input pattern) that will be aggregated and returned as the final output of the attention mechanism. This is the data the model will focus on based on the attention scores.

#### General Structure and Dimensions

1. **Input:**
   - Suppose we have a sequence of $n$ input tokens (e.g., words in a sentence).
   - Each input token $x_i$ is typically represented as a vector of size $d_{\text{model}}$, where $d_{\text{model}}$ is the dimensionality of the input embeddings.

2. **Query, Key, and Value Dimensions:**
   - For each token $x_i$, the model computes the Query, Key, and Value vectors through linear transformations of the input embedding.
   - These vectors usually have the following dimensions:
     - **Query (Q):** $Q \in \mathbb{R}^{n \times d_k}$
     - **Key (K):** $K \in \mathbb{R}^{n \times d_k}$
     - **Value (V):** $V \in \mathbb{R}^{n \times d_v}$
   
   Here:
   - $n$ is the number of tokens (length of the input sequence).
   - $d_k$ is the dimensionality of the Key and Query vectors.
   - $d_v$ is the dimensionality of the Value vectors.

   **Note:** Typically, $d_k = d_v$, but they can differ.

3. **Attention Score Calculation:**
   - To compute attention scores, we calculate the similarity between the Query and Key vectors.
   - If we are computing dot product attention, the score for each token is computed as $Q_i \cdot K_j$, which results in a scalar value.
   - This results in an attention score matrix of size $n \times n$ (since we compute scores for each pair of tokens).

4. **Softmax and Weighted Sum:**
   - The attention scores are normalized using softmax, yielding a weight matrix of size $n \times n$.
   - These weights are then used to compute the weighted sum of the Value vectors, producing an output of size $n \times d_v$.

#### Example with Dimensions

Let’s assume:
- **Number of tokens (n):** 4 (e.g., a sentence with 4 words).
- **Embedding dimension (d_model):** 512.
- **Query/Key dimension (d_k):** 64.
- **Value dimension (d_v):** 128.

Given this:
1. **Input Embeddings:**
   - The input sequence would be represented as a matrix $X \in \mathbb{R}^{4 \times 512}$.

2. **Query, Key, Value:**
   - The Query matrix $Q$ after transformation would be $Q \in \mathbb{R}^{4 \times 64}$.
   - The Key matrix $K$ would be $K \in \mathbb{R}^{4 \times 64}$.
   - The Value matrix $V$ would be $V \in \mathbb{R}^{4 \times 128}$.

3. **Attention Scores:**
   - The dot product of $Q$ and $K^T$ (transpose of $K$) would still yield an attention score matrix of size $4 \times 4$.

4. **Output:**
   - The final output after applying softmax and weighting the values would now be of size $4 \times 128$, corresponding to the aggregated representation of the input sequence.


In [ ]:
import numpy as np

# Define dimensions
n_tokens = 5
d_model = 4
d_k = 2
d_v = 3

# Random seed for reproducibility
np.random.seed(42)

# Input embeddings (5 tokens, each of dimension 4)
X = np.random.rand(n_tokens, d_model)

# Linear transformations for Query, Key, and Value
W_Q = np.random.rand(d_model, d_k)
W_K = np.random.rand(d_model, d_k)
W_V = np.random.rand(d_model, d_v)

# Compute Query, Key, and Value matrices
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# Compute attention scores (dot product of Q and K^T)
scores = Q @ K.T

# Apply softmax to scores for each row
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

attention_weights = softmax(scores)

# Compute the output as a weighted sum of V
output = attention_weights @ V

print("Input Embeddings (X):\n", X)
print("\nQuery Matrix (Q):\n", Q)
print("\nKey Matrix (K):\n", K)
print("\nValue Matrix (V):\n", V)
print("\nAttention Scores:\n", scores)
print("\nAttention Weights:\n", attention_weights)
print("\nOutput:\n", output)


Input Embeddings (X):
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]

Query Matrix (Q):
 [[0.96028642 1.28314635]
 [0.34047628 0.56993754]
 [0.77770711 0.85818613]
 [0.69091216 0.43099109]
 [0.59460426 0.72360356]]

Key Matrix (K):
 [[1.42518579 1.35804966]
 [1.02738725 0.78917716]
 [1.72421022 0.95227038]
 [0.81108596 0.39567105]
 [0.8083695  0.74891105]]

Value Matrix (V):
 [[0.95434613 1.00483113 1.227813  ]
 [0.69204521 0.35708928 0.64949938]
 [1.13806258 0.46617365 1.27166989]
 [0.47479735 0.32972629 0.81716565]
 [0.53144897 0.5773121  0.73125755]]

Attention Scores:
 [[3.11116303 1.99921581 2.87763792 1.28657869 1.73722874]
 [1.25924544 0.79958268 1.12978732 0.50166331 0.70206317]
 [2.2738365  1.47626726 2.15815578 0.97034672 1.27137979]
 [1.5699855  1.04996267 1.60169785 0.73091984 0.88128631

# Multihead Attention Mechanism: Input, Matrix Dimensions, and Resultant Dimensions

The Multihead Attention mechanism in the Transformer model allows the model to focus on different parts of the input sequence simultaneously. Here's a detailed breakdown of the input, matrix dimensions, and resultant dimensions, including where and how the softmax is applied.

## 1. **Input**

The input to the Multihead Attention mechanism is typically a sequence of token embeddings. For natural language processing tasks, these could be word or subword embeddings.

- **Input Tensor**: $(B \times L \times d_{\text{model}})$
  - $B$: Batch size (number of sequences processed in parallel).
  - $L$: Sequence length (number of tokens in each sequence).
  - $d_{\text{model}}$: Model dimension (embedding dimension for each token).

## 2. **Linear Projections to Query, Key, and Value Matrices**

The input sequence is transformed into Query (Q), Key (K), and Value (V) matrices through learned linear transformations.

- **Query (Q)**:
  - Linear transformation using a weight matrix $W_Q \in \mathbb{R}^{d_{\text{model}} \times d_k}$.
  - **Q = X * W_Q**
  - Resulting shape: $Q = (B \times L \times d_k)$

- **Key (K)**:
  - Linear transformation using a weight matrix $W_K \in \mathbb{R}^{d_{\text{model}} \times d_k}$.
  - **K = X * W_K**
  - Resulting shape: $K = (B \times L \times d_k)$

- **Value (V)**:
  - Linear transformation using a weight matrix $W_V \in \mathbb{R}^{d_{\text{model}} \times d_v}$.
  - **V = X * W_V**
  - Resulting shape: $V = (B \times L \times d_v)$

Here, $d_k = d_v = \frac{d_{\text{model}}}{h}$, where $h$ is the number of attention heads.

## 3. **Scaled Dot-Product Attention**

### 3.1. **Attention Scores (QK$^T$)**

The attention scores are calculated as the dot product of the Query matrix $Q$ and the transpose of the Key matrix $K^T$, scaled by $\frac{1}{\sqrt{d_k}}$ to prevent large values that could destabilize the softmax.

- **Q × K$^T$**:
  - Q: $(B \times L \times d_k)$
  - K$^T$: $(B \times d_k \times L)$
  - Resulting shape: $(B \times L \times L)$

This gives us an attention score matrix of shape $(B \times L \times L)$, where each element represents the attention score between a pair of tokens in the sequence.

### 3.2. **Softmax on Attention Scores**

The softmax function is applied along the last dimension of the attention score matrix (i.e., across the sequence length $L$) to normalize the scores into probabilities. The softmax is applied separately for each token in the sequence to determine the importance of every other token in the sequence relative to it.

- **Softmax(Q × K$^T$)**:
  - Input shape: $(B \times L \times L)$
  - Output shape: $(B \times L \times L)$

Each row in the resulting attention weight matrix represents the attention distribution over all tokens for a specific token in the sequence.

### 3.3. **Weighted Sum with Value Matrix (V)**

The attention weights are used to compute a weighted sum of the Value (V) vectors, producing the final output for each head.

- **Attention Output = Attention Weights × V**:
  - Attention Weights: $(B \times L \times L)$
  - $V$: $(B \times L \times d_v)$
  - Resulting shape: $(B \times L \times d_v)$

This gives us the output for a single attention head.

## 4. **Multihead Attention**

In Multihead Attention, multiple attention heads are computed in parallel, each with its own set of Query, Key, and Value matrices. After calculating the attention outputs for all heads, these outputs are concatenated and passed through a final linear layer.

### 4.1. **Concatenation of Heads**

After calculating the attention output for each head, the outputs are concatenated along the last dimension:

- **Concatenated Output**: $(B \times L \times (h \times d_v))$
  - Since $d_v = \frac{d_{\text{model}}}{h}$, the concatenated dimension becomes $h \times d_v = d_{\text{model}}$.

### 4.2. **Final Linear Projection**

The concatenated output is passed through a final linear layer to project it back to the original model dimension:

- **Weight Matrix $W_O$**: The final output weight matrix has dimensions $W_O \in \mathbb{R}^{(h \times d_v) \times d_{\text{model}}}$.
- **Final Output Calculation**:
  - The concatenated output is multiplied by $W_O$ to project it back to $d_{\text{model}}$.
  - **Final Output = Concatenated Output * $W_O$**
  - Resulting shape: $(B \times L \times d_{\text{model}})$

## Summary of Resultant Dimensions

- **Input**: $B \times L \times d_{\text{model}}$
- **Q, K, V matrices**: $B \times L \times d_k$ (per head)
- **Attention Scores (QK$^T$)**: $B \times L \times L$
- **Attention Output (per head)**: $B \times L \times d_v$
- **Concatenated Output**: $B \times L \times d_{\text{model}}$
- **Final Multihead Attention Output**: $B \times L \times d_{\text{model}}$

The Multihead Attention mechanism enables the model to focus on different parts of the input sequence in parallel, making it a powerful tool for capturing complex relationships in the data.


In [ ]:
from IPython.display import HTML
svg_code = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><defs><marker id="arrowhead" markerWidth="10" markerHeight="7" refX="0" refY="3.5" orient="auto"><polygon points="0 0, 10 3.5, 0 7" fill="#000"/></marker></defs><rect x="10" y="50" width="100" height="60" fill="#f0f0f0" stroke="#000"/><text x="60" y="85" text-anchor="middle">Input</text><text x="60" y="100" text-anchor="middle" font-size="10">B×L×d_model</text><rect x="170" y="20" width="100" height="40" fill="#e6f3ff" stroke="#000"/><text x="220" y="45" text-anchor="middle" font-size="12">Linear (Q)</text><rect x="170" y="70" width="100" height="40" fill="#e6f3ff" stroke="#000"/><text x="220" y="95" text-anchor="middle" font-size="12">Linear (K)</text><rect x="170" y="120" width="100" height="40" fill="#e6f3ff" stroke="#000"/><text x="220" y="145" text-anchor="middle" font-size="12">Linear (V)</text><rect x="330" y="20" width="80" height="40" fill="#ffe6e6" stroke="#000"/><text x="370" y="45" text-anchor="middle" font-size="12">Q</text><rect x="330" y="70" width="80" height="40" fill="#e6ffe6" stroke="#000"/><text x="370" y="95" text-anchor="middle" font-size="12">K</text><rect x="330" y="120" width="80" height="40" fill="#e6e6ff" stroke="#000"/><text x="370" y="145" text-anchor="middle" font-size="12">V</text><rect x="470" y="20" width="120" height="140" fill="#fff0e6" stroke="#000"/><text x="530" y="45" text-anchor="middle" font-size="14">Attention Heads</text><text x="530" y="65" text-anchor="middle" font-size="12">Head 1</text><text x="530" y="95" text-anchor="middle" font-size="12">Head 2</text><text x="530" y="125" text-anchor="middle" font-size="12">...</text><text x="530" y="150" text-anchor="middle" font-size="12">Head h</text><rect x="650" y="70" width="100" height="40" fill="#f0e6ff" stroke="#000"/><text x="700" y="95" text-anchor="middle" font-size="12">Concatenate</text><rect x="650" y="150" width="100" height="40" fill="#e6f3ff" stroke="#000"/><text x="700" y="175" text-anchor="middle" font-size="12">Linear</text><rect x="650" y="230" width="100" height="60" fill="#f0f0f0" stroke="#000"/><text x="700" y="260" text-anchor="middle">Output</text><text x="700" y="275" text-anchor="middle" font-size="10">B×L×d_model</text><line x1="110" y1="80" x2="170" y2="40" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="110" y1="80" x2="170" y2="90" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="110" y1="80" x2="170" y2="140" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="270" y1="40" x2="330" y2="40" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="270" y1="90" x2="330" y2="90" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="270" y1="140" x2="330" y2="140" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="410" y1="40" x2="470" y2="40" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="410" y1="90" x2="470" y2="90" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="410" y1="140" x2="470" y2="140" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="590" y1="90" x2="650" y2="90" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="700" y1="110" x2="700" y2="150" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><line x1="700" y1="190" x2="700" y2="230" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/><text x="140" y="30" text-anchor="middle" font-size="10">B×L×d_model</text><text x="300" y="30" text-anchor="middle" font-size="10">B×L×d_k</text><text x="300" y="80" text-anchor="middle" font-size="10">B×L×d_k</text><text x="300" y="130" text-anchor="middle" font-size="10">B×L×d_v</text><text x="620" y="70" text-anchor="middle" font-size="10">B×L×d_v</text><text x="620" y="230" text-anchor="end" font-size="10">B×L×(h×d_v)</text></svg>"""
HTML(f"""
<div style="width:800px; height:600px;">
  {svg_code}
</div>
""")

In [ ]:
from IPython.display import HTML

svg_code = """
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000">
  <defs>
    <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="0" refY="3.5" orient="auto">
      <polygon points="0 0, 10 3.5, 0 7" fill="#000"/>
    </marker>
  </defs>

  <!-- Encoder -->
  <rect x="50" y="50" width="300" height="400" fill="#f0f0f0" stroke="#000" stroke-width="2"/>
  <text x="200" y="80" text-anchor="middle" font-size="20" font-weight="bold">Encoder</text>

  <!-- Encoder Input -->
  <rect x="100" y="100" width="200" height="40" fill="#e6f3ff" stroke="#000"/>
  <text x="200" y="125" text-anchor="middle">Input Embedding</text>
  <text x="200" y="140" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Positional Encoding -->
  <rect x="100" y="160" width="200" height="40" fill="#ffe6e6" stroke="#000"/>
  <text x="200" y="185" text-anchor="middle">Positional Encoding</text>
  <text x="200" y="200" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Multi-Head Attention -->
  <rect x="100" y="220" width="200" height="40" fill="#e6ffe6" stroke="#000"/>
  <text x="200" y="245" text-anchor="middle">Multi-Head Attention</text>
  <text x="200" y="260" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Add & Norm -->
  <rect x="100" y="280" width="200" height="40" fill="#e6e6ff" stroke="#000"/>
  <text x="200" y="305" text-anchor="middle">Add & Norm</text>
  <text x="200" y="320" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Feed Forward -->
  <rect x="100" y="340" width="200" height="40" fill="#fff0e6" stroke="#000"/>
  <text x="200" y="365" text-anchor="middle">Feed Forward</text>
  <text x="200" y="380" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Add & Norm -->
  <rect x="100" y="400" width="200" height="40" fill="#e6e6ff" stroke="#000"/>
  <text x="200" y="425" text-anchor="middle">Add & Norm</text>
  <text x="200" y="440" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Decoder -->
  <rect x="450" y="50" width="300" height="600" fill="#f0f0f0" stroke="#000" stroke-width="2"/>
  <text x="600" y="80" text-anchor="middle" font-size="20" font-weight="bold">Decoder</text>

  <!-- Decoder Input -->
  <rect x="500" y="100" width="200" height="40" fill="#e6f3ff" stroke="#000"/>
  <text x="600" y="125" text-anchor="middle">Output Embedding</text>
  <text x="600" y="140" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Positional Encoding -->
  <rect x="500" y="160" width="200" height="40" fill="#ffe6e6" stroke="#000"/>
  <text x="600" y="185" text-anchor="middle">Positional Encoding</text>
  <text x="600" y="200" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Masked Multi-Head Attention -->
  <rect x="500" y="220" width="200" height="40" fill="#e6ffe6" stroke="#000"/>
  <text x="600" y="245" text-anchor="middle">Masked Multi-Head Attention</text>
  <text x="600" y="260" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Add & Norm -->
  <rect x="500" y="280" width="200" height="40" fill="#e6e6ff" stroke="#000"/>
  <text x="600" y="305" text-anchor="middle">Add & Norm</text>
  <text x="600" y="320" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Multi-Head Attention -->
  <rect x="500" y="340" width="200" height="40" fill="#e6ffe6" stroke="#000"/>
  <text x="600" y="365" text-anchor="middle">Multi-Head Attention</text>
  <text x="600" y="380" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Add & Norm -->
  <rect x="500" y="400" width="200" height="40" fill="#e6e6ff" stroke="#000"/>
  <text x="600" y="425" text-anchor="middle">Add & Norm</text>
  <text x="600" y="440" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Feed Forward -->
  <rect x="500" y="460" width="200" height="40" fill="#fff0e6" stroke="#000"/>
  <text x="600" y="485" text-anchor="middle">Feed Forward</text>
  <text x="600" y="500" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Add & Norm -->
  <rect x="500" y="520" width="200" height="40" fill="#e6e6ff" stroke="#000"/>
  <text x="600" y="545" text-anchor="middle">Add & Norm</text>
  <text x="600" y="560" text-anchor="middle" font-size="10">(batch_size, seq_len, d_model)</text>

  <!-- Linear -->
  <rect x="500" y="580" width="200" height="40" fill="#f0e6ff" stroke="#000"/>
  <text x="600" y="605" text-anchor="middle">Linear</text>
  <text x="600" y="620" text-anchor="middle" font-size="10">(batch_size, seq_len, vocab_size)</text>

  <!-- Softmax -->
  <rect x="500" y="640" width="200" height="40" fill="#e6fff0" stroke="#000"/>
  <text x="600" y="665" text-anchor="middle">Softmax</text>
  <text x="600" y="680" text-anchor="middle" font-size="10">(batch_size, seq_len, vocab_size)</text>

  <!-- Arrows -->
  <!-- Encoder -->
  <line x1="200" y1="140" x2="200" y2="160" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="200" y1="200" x2="200" y2="220" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="200" y1="260" x2="200" y2="280" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="200" y1="320" x2="200" y2="340" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="200" y1="380" x2="200" y2="400" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>

  <!-- Decoder -->
  <line x1="600" y1="140" x2="600" y2="160" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="200" x2="600" y2="220" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="260" x2="600" y2="280" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="320" x2="600" y2="340" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="380" x2="600" y2="400" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="440" x2="600" y2="460" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="500" x2="600" y2="520" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="560" x2="600" y2="580" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
  <line x1="600" y1="620" x2="600" y2="640" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>

  <!-- Encoder to Decoder -->
  <line x1="300" y1="420" x2="500" y2="360" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>

  <!-- Output -->
  <rect x="500" y="700" width="200" height="40" fill="#f0f0f0" stroke="#000"/>
  <text x="600" y="725" text-anchor="middle">Output Probabilities</text>
  <text x="600" y="740" text-anchor="middle" font-size="10">(batch_size, seq_len, vocab_size)</text>

  <line x1="600" y1="680" x2="600" y2="700" stroke="#000" stroke-width="2" marker-end="url(#arrowhead)"/>
</svg>
"""

HTML(f"""
<div style="width:800px; height:1000px;">
  {svg_code}
</div>
""")

In [ ]:
from IPython.display import HTML

svg_code = """
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000">
  <!-- Paste the entire SVG code here -->
</svg>
"""

HTML(f"""
<div style="width:800px; height:1000px;">
  {svg_code}
</div>
""")