# Logistic Regression and Iteratively Reweighted Least Squares (IRLS)

## Mathematical Basis of Logistic Regression

Logistic regression is a statistical method used for binary classification, where the outcome is a binary variable (i.e., it takes on two possible outcomes such as 0 or 1, true or false, success or failure). Unlike linear regression, which predicts continuous values, logistic regression predicts the probability that a given input point belongs to a certain class.

### Logistic Regression Model

1. **Logit Function:**
   Logistic regression is based on the logistic function, also known as the sigmoid function, which maps any real-valued number into the (0, 1) interval:

   $\sigma(z) = \frac{1}{1 + e^{-z}}$

2. **Linear Combination of Inputs:**
   The input to the logistic function is a linear combination of the input features (X):

   $z = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_n X_n$

   Here, $\beta_0, \beta_1, \ldots, \beta_n$ are the coefficients (parameters) of the model.

3. **Probability Estimation:**
   The logistic function outputs a value between 0 and 1, which can be interpreted as the probability $p$ that the given input point belongs to the class labeled 1 (or true, success, etc.):

   $p = \frac{1}{1 + e^{-(\beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_n X_n)}}$

4. **Log-Odds:**
   The log-odds (or logit) is the logarithm of the odds of the event:

   $\text{logit}(p) = \ln\left(\frac{p}{1 - p}\right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_n X_n$

   This linear relationship between the log-odds and the input features allows for straightforward interpretation of the model parameters.

5. **Maximum Likelihood Estimation (MLE):**
   The parameters $\beta$ are estimated using Maximum Likelihood Estimation. The likelihood function for logistic regression is given by:

   $L(\beta) = \prod_{i=1}^{m} p_i^{y_i} (1 - p_i)^{1 - y_i}$

   where $m$ is the number of training samples, $y_i$ is the actual binary outcome (0 or 1) for the $i$-th sample, and $p_i$ is the predicted probability for the $i$-th sample.

   The log-likelihood is often used to simplify the computation:

   $\ell(\beta) = \sum_{i=1}^{m} \left[ y_i \ln(p_i) + (1 - y_i) \ln(1 - p_i) \right]$

6. **Optimization:**
   The log-likelihood function is maximized with respect to $\beta$ to find the best-fitting parameters. This is typically done using iterative optimization algorithms such as Gradient Descent, Newton-Raphson, or other numerical methods.

### Optimization: Finding the Best-Fitting Parameters

#### Log-Likelihood Function

The log-likelihood function for logistic regression, which we aim to maximize, is:

$\ell(\beta) = \sum_{i=1}^{m} \left[ y_i \ln(p_i) + (1 - y_i) \ln(1 - p_i) \right]$

where:
- $m$ is the number of training samples.
- $y_i$ is the actual binary outcome (0 or 1) for the $i$-th sample.
- $p_i$ is the predicted probability for the $i$-th sample, which is given by the logistic function:

$p_i = \frac{1}{1 + e^{-z_i}} \quad \text{where} \quad z_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \cdots + \beta_n X_{in}$

#### Gradient of the Log-Likelihood

To maximize the log-likelihood function, we need to find its gradient with respect to the parameters $\beta$. The gradient vector $\nabla \ell(\beta)$ consists of the partial derivatives of $\ell(\beta)$ with respect to each $\beta_j$:

$\frac{\partial \ell(\beta)}{\partial \beta_j} = \sum_{i=1}^{m} \left( y_i - p_i \right) X_{ij}$

where $X_{ij}$ is the $j$-th feature of the $i$-th sample.

#### Hessian Matrix

For methods like Newton-Raphson, we also need the Hessian matrix $H(\beta)$, which is the matrix of second-order partial derivatives of the log-likelihood function. Each element of the Hessian matrix $H_{jk}$ is given by:

$H_{jk} = \frac{\partial^2 \ell(\beta)}{\partial \beta_j \partial \beta_k} = -\sum_{i=1}^{m} p_i (1 - p_i) X_{ij} X_{ik}$

#### Optimization Algorithms

There are several optimization algorithms that can be used to maximize the log-likelihood function:

**Gradient Descent:**

Gradient descent is an iterative optimization algorithm that updates the parameters in the direction of the gradient of the log-likelihood function. The update rule for gradient descent is:

$\beta_j^{(t+1)} = \beta_j^{(t)} + \eta \frac{\partial \ell(\beta)}{\partial \beta_j}$

where:
- $\eta$ is the learning rate.
- $\beta_j^{(t)}$ is the value of $\beta_j$ at iteration $t$.

**Newton-Raphson Method:**

Newton-Raphson is an iterative method that uses both the gradient and the Hessian matrix to find the maximum of the log-likelihood function. The update rule for Newton-Raphson is:

$\beta^{(t+1)} = \beta^{(t)} - H^{-1}(\beta^{(t)}) \nabla \ell(\beta^{(t)})$

where:
- $H(\beta^{(t)})$ is the Hessian matrix at iteration $t$.
- $\nabla \ell(\beta^{(t)})$ is the gradient vector at iteration $t$.

**Iteratively Reweighted Least Squares (IRLS):**

IRLS is another method specifically designed for logistic regression. It iteratively solves weighted least squares problems, where the weights are updated based on the current estimate of the probabilities $p_i$. The IRLS update rule is:

$\beta^{(t+1)} = \beta^{(t)} + (X^T W X)^{-1} X^T (y - p)$

where:
- $X$ is the design matrix (matrix of input features).
- $W$ is a diagonal matrix of weights with $W_{ii} = p_i (1 - p_i)$.
- $y$ is the vector of actual binary outcomes.
- $p$ is the vector of predicted probabilities.

### Iteratively Reweighted Least Squares (IRLS) for Logistic Regression

IRLS is a method specifically designed for fitting generalized linear models, including logistic regression. It is particularly effective for logistic regression because it transforms the problem into a series of weighted least squares problems, which are easier to solve iteratively. Here's a detailed explanation of how IRLS works in the context of logistic regression:

#### Logistic Regression Model Recap

In logistic regression, the probability $p_i$ that the $i$-th observation belongs to the class labeled 1 is modeled as:

$p_i = \frac{1}{1 + e^{-z_i}} \quad \text{where} \quad z_i = \beta_0 + \beta_1 X_{i1} + \beta_2 X_{i2} + \cdots + \beta_n X_{in}$

The log-likelihood function to be maximized is:

$\ell(\beta) = \sum_{i=1}^{m} \left[ y_i \ln(p_i) + (1 - y_i) \ln(1 - p_i) \right]$

#### Newton-Raphson Update

The Newton-Raphson method for updating the parameters involves both the gradient vector $\nabla \ell(\beta)$ and the Hessian matrix $H(\beta)$. The update rule is:

$\beta^{(t+1)} = \beta^{(t)} - H^{-1}(\beta^{(t)}) \nabla \ell(\beta^{(t)})$

#### IRLS as a Special Case of Newton-Raphson

IRLS simplifies the Newton-Raphson method by focusing on weighted least squares solutions. Here's how IRLS operates step by step:

1. **Initialize Parameters:**
   Start with an initial guess for the parameters $\beta$.

2. **Compute Weights:**
   For the current parameter estimates $\beta^{(t)}$, compute the predicted probabilities $p_i$:

   $p_i^{(t)} = \frac{1}{1 + e^{-z_i^{(t)}}}$

   Then compute the weights $w_i$:

   $w_i = p_i^{(t)} (1 - p_i^{(t)})$

   Construct the diagonal weight matrix $W$:

   $W = \text{diag}(w_1, w_2, \ldots, w_m)$

3. **Update Parameters:**
   Solve the weighted least squares problem to update the parameters:

   $\beta^{(t+1)} = \beta^{(t)} + (X^T W X)^{-1} X^T (y - p^{(t)})$

   Here:
   - $X$ is the design matrix.
   - $y$ is the vector of observed outcomes.
   - $p^{(t)}$ is the vector of predicted probabilities at iteration $t$.

4. **Iterate:**
   Repeat steps 2 and 3 until convergence, i.e., until the parameter estimates $\beta$ stabilize and the changes become negligibly small.

#### Benefits of IRLS

- **Efficiency:**
  IRLS is computationally efficient because it reduces the problem to a series of linear algebra operations, which are well-optimized and can be solved quickly.

- **Stability:**
  IRLS tends to be numerically stable and converges quickly, especially when the initial parameter estimates are reasonably close to the true values.

- **Handling of Weights:**
  The iterative weighting process ensures that the model focuses more on observations where the current fit is poor, improving overall accuracy.

### Multinomial Logistic Regression

Multinomial logistic regression is an extension of binary logistic regression that handles multi-class classification problems. Instead of a binary outcome, the dependent variable can take on three or more categories. The approach generalizes the logistic regression model to accommodate multiple classes.

#### Model Formulation

For a multi-class problem with $K$ classes, we model the log-odds of each class relative to a reference class (typically the last class, $K$). The log-odds for class $k$ (where $k = 1, 2, \ldots, K-1$) are given by:

$\ln\left(\frac{P(Y = k | X)}{P(Y = K | X)}\right) = \beta_{k0} + \beta_{k1} X_1 + \beta_{k2} X_2 + \cdots + \beta_{kn} X_n$

This can be rewritten as:

$z_k = \beta_{k0} + \beta_{k1} X_1 + \beta_{k2} X_2 + \cdots + \beta_{kn} X_n$

#### Probability Calculation

The probabilities for each class are computed using the softmax function:

$P(Y = k | X) = \frac{e^{z_k}}{\sum_{j=1}^K e^{z_j}}$

Note that for the reference class $K$, $z_K = 0$ (since $\beta_K = 0$).

#### Estimation of Parameters

Similar to binary logistic regression, the parameters $\beta_{kj}$ are estimated using maximum likelihood estimation. The log-likelihood function for the multinomial case is:

$\ell(\beta) = \sum_{i=1}^{m} \sum_{k=1}^{K} y_{ik} \ln(P(Y = k | X_i))$

where $y_{ik}$ is an indicator variable that equals 1 if observation $i$ belongs to class $k$, and 0 otherwise.

#### Prediction

To predict the class for a new observation $X_{\text{new}}$, we calculate the probabilities for each class using the estimated parameters and then choose the class with the highest probability. The steps are as follows:

1. **Compute Linear Predictors:**
   For a new observation $X_{\text{new}}$, compute the linear predictors for each class (excluding the reference class):

   $z_{k, \text{new}} = \beta_{k0} + \beta_{k1} X_{1, \text{new}} + \beta_{k2} X_{2, \text{new}} + \cdots + \beta_{kn} X_{n, \text{new}}$

2. **Calculate Probabilities:**
   Calculate the probabilities for each class using the softmax function:

   $p_{k, \text{new}} = \frac{e^{z_{k, \text{new}}}}{\sum_{j=1}^K e^{z_{j, \text{new}}}}$

   Note that for the reference class, $z_{K, \text{new}} = 0$ (since $\beta_K = 0$).

3. **Class Prediction:**
   Predict the class with the highest probability:

   $\text{Predicted Class} = \arg\max_k p_{k, \text{new}}$

## Advantages and Limitations of Logistic Regression

### Advantages

1. **Simplicity:**
   Logistic regression is easy to implement and interpret, especially for binary classification problems.

2. **Probabilistic Interpretation:**
   The model provides probability estimates for class membership, which can be useful in many applications.

3. **Feature Importance:**
   The coefficients of the logistic regression model indicate the strength and direction of the relationship between each feature and the outcome.

4. **Generalization:**
   Logistic regression tends to generalize well to new data if the linear assumption is reasonable.

### Limitations

1. **Linearity Assumption:**
   Logistic regression assumes a linear relationship between the input features and the log-odds of the outcome, which may not hold in practice.

2. **Limited to Binary or Multinomial Outcomes:**
   While it can be extended to multinomial outcomes, logistic regression is inherently designed for binary classification.

3. **Feature Scaling:**
   The model can be sensitive to the scale of the input features, often requiring standardization or normalization.

4. **Outliers:**
   Logistic regression can be affected by outliers, which can disproportionately influence the parameter estimates.

### Conclusion

Logistic regression is a powerful and widely-used method for binary and multinomial classification problems. Its probabilistic interpretation, ease of implementation, and ability to handle a variety of real-world problems make it a go-to choice for many practitioners. However, it is important to be aware of its assumptions and limitations and consider alternative models when those assumptions are violated or the limitations are significant.


In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

def sigmoid(z):
    return 1 / (1 + np.exp(-np.clip(z, -250, 250)))

def logistic_regression_irls(X, y, max_iter=100, tol=1e-6, alpha=0.1):
    n_samples, n_features = X.shape
    beta = np.zeros(n_features)

    for _ in range(max_iter):
        z = X @ beta
        p = sigmoid(z)
        w = p * (1 - p)

        W = np.diag(w)
        XTW = X.T @ W

        # Add L2 regularization term
        H = XTW @ X + alpha * np.eye(n_features)
        g = X.T @ (y - p) - alpha * beta

        # Use pseudo-inverse for better stability
        beta_new = beta + np.linalg.pinv(H) @ g

        if np.linalg.norm(beta_new - beta) < tol:
            break

        beta = beta_new

    return beta

def predict(X, beta):
    return (sigmoid(X @ beta) >= 0.5).astype(int)

# Load the Iris dataset
iris = load_iris()
X = iris.data[:, [0, 2]]  # We'll use sepal length and petal length
y = (iris.target == 0).astype(int)  # Binary classification: Iris Setosa vs others

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Add bias term
X_train_scaled = np.hstack([np.ones((X_train_scaled.shape[0], 1)), X_train_scaled])
X_test_scaled = np.hstack([np.ones((X_test_scaled.shape[0], 1)), X_test_scaled])

# Train the model
beta = logistic_regression_irls(X_train_scaled, y_train)

# Make predictions
y_train_pred = predict(X_train_scaled, beta)
y_test_pred = predict(X_test_scaled, beta)

# Evaluate the model
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Train Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_test_pred))

# Display the learned parameters
print("\nLearned Parameters (Beta):")
print(f"Intercept: {beta[0]:.4f}")
print(f"Sepal Length: {beta[1]:.4f}")
print(f"Petal Length: {beta[2]:.4f}")

Train Accuracy: 1.0000
Test Accuracy: 1.0000

Confusion Matrix (Test Set):
[[20  0]
 [ 0 10]]

Learned Parameters (Beta):
Intercept: -3.3135
Sepal Length: 0.1344
Petal Length: -6.0009


In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

def multinomial_logistic_regression_irls(X, y, n_classes, max_iter=100, tol=1e-6, alpha=0.1):
    n_samples, n_features = X.shape
    beta = np.zeros((n_features, n_classes))

    for _ in range(max_iter):
        z = X @ beta
        p = softmax(z)

        beta_old = beta.copy()

        for k in range(n_classes):
            y_k = (y == k).astype(int)
            p_k = p[:, k]
            w_k = p_k * (1 - p_k)

            W = np.diag(w_k)
            XTW = X.T @ W

            # Add L2 regularization term
            H = XTW @ X + alpha * np.eye(n_features)
            g = X.T @ (y_k - p_k) - alpha * beta[:, k]

            # Use pseudo-inverse for better stability
            beta[:, k] += np.linalg.pinv(H) @ g

        if np.linalg.norm(beta - beta_old) < tol:
            break

    return beta

def predict(X, beta):
    return np.argmax(softmax(X @ beta), axis=1)

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Add bias term
X_train_scaled = np.hstack([np.ones((X_train_scaled.shape[0], 1)), X_train_scaled])
X_test_scaled = np.hstack([np.ones((X_test_scaled.shape[0], 1)), X_test_scaled])

# Train the model
n_classes = len(np.unique(y))
beta = multinomial_logistic_regression_irls(X_train_scaled, y_train, n_classes)

# Make predictions
y_train_pred = predict(X_train_scaled, beta)
y_test_pred = predict(X_test_scaled, beta)

# Evaluate the model
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Train Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

print("\nConfusion Matrix (Test Set):")
print(confusion_matrix(y_test, y_test_pred))

# Display the learned parameters
print("\nLearned Parameters (Beta):")
feature_names = ['Bias'] + iris.feature_names
for i, feature in enumerate(feature_names):
    print(f"{feature}:")
    for j, class_name in enumerate(iris.target_names):
        print(f"  {class_name}: {beta[i, j]:.4f}")

Train Accuracy: 0.9750
Test Accuracy: 1.0000

Confusion Matrix (Test Set):
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Learned Parameters (Beta):
Bias:
  setosa: -0.2362
  versicolor: 3.3165
  virginica: -3.6652
sepal length (cm):
  setosa: -1.5058
  versicolor: 0.9247
  virginica: 0.2872
sepal width (cm):
  setosa: 1.8943
  versicolor: -0.1311
  virginica: -1.4151
petal length (cm):
  setosa: -3.3626
  versicolor: -1.1719
  virginica: 4.1052
petal width (cm):
  setosa: -3.1386
  versicolor: -1.2059
  virginica: 3.9824
